### ISSUE TITLE
`display-p3` color input shorter than `lab` output

### ISSUE THREAD

**Issue by argyleink** [parcel-bundler/parcel-css#108]
[parcel-css repro link](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%3Aroot%20%7B%5Cn%20%20--link%3A%20color(display-p3%200%20.5%201)%3B%5Cn%20%20--link-visited%3A%20color(display-p3%20.6%20.2%201)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)

i could see this being marked as "wont fix", but thought you'd be interested to see how many more characters the converted colors to lab are.

**Comment by devongovett** [comment]
Thanks for the report! I improved it a bit in the above commit so that the original will be preserved. Fallbacks are now generated in levels: Oklab -> Lab -> P3 -> RGB. We start with all levels below and including the authored color space, and remove the ones that aren't compatible with the browser targets.
