### ISSUE TITLE
How to Watch files when parcel-css is used independently?

### ISSUE THREAD

**Issue by cvkmohan** [parcel-bundler/parcel-css#126]
I would want to use parcel-css only for css processing. From the documentation, I understood that, we can use via ```npx```. If we are using in that method, how do we watch and rebuild when we make changes?

**Comment by joshstoik1** [comment]
A typical Node setup would leverage something like [npm-watch](https://www.npmjs.com/package/npm-watch) to trigger specific tasks when files change. If you'd prefer to leave Node out of it, [watchexec](https://github.com/watchexec/watchexec) CLI should do the trick. :wink:

For best results, your workflow should probably watch for `*.css` changes in one directory and write minified versions to another, otherwise the watcher might fall into a loop (since minification is itself a change).

**Comment by cvkmohan** [comment]
Thanks @joshstoik1. Looks like ```npm-watch``` might be the way to go. My use case is in a Phoenix application. JS processing is handled by ```esbuild```. If I want to use ```tailwindcss``` directly - I am using ```tailwind-cli```. However, ```tailwind-cli``` supports only internal plugins. If I want to use ```daisyui``` then I have to go the full node route - and may be ```vite``` or ```webpack```. I thought ```parcel-css``` has a great role there. So, trying to see if I can use it only for processing css.

If you have any further inputs please let me know. I will update my results of the experiment here. Till then I will be closing the issue.
