### ISSUE TITLE
How can we get location of each AST node?

### ISSUE THREAD

**Issue by g-plane** [parcel-bundler/parcel-css#168]
From the [Rust doc](https://docs.rs/parcel_css/1.0.0-alpha.24/parcel_css/index.html), it looks that only rules contain a field called `location`, while other AST nodes don't. How can I get location for any type of AST node?

**Comment by devongovett** [comment]
At the moment you can't because source maps aren't that granular anyway. What are you trying to do?

**Comment by g-plane** [comment]
Making a linter which requires location information to tell users where is wrong.

**Comment by devongovett** [comment]
How granular do you need? Would properties be enough, or you need each individual value within a property too? I wanted to avoid adding these in most places because they take up a bunch of memory and are rarely used except in errors. If possible, I'd probably prefer to re-calculate the location when it is requested. There are a ton of different node types, so adding it everywhere would probably be a lot of work. If properties are close enough, we could probably do that fairly easily.

**Comment by g-plane** [comment]
Certainly, I know it would be a lot of work and may impact the performance, so properties may be OK. (At least users know where they can fix.) And, I think it can even be property-key only or property-value only? For example:

Property-key only:

```css
a {
  color: red;
  ^^^^^
}
```

Property-value only:

```css
a {
  color: red;
         ^^^
}
```

Will it be hard or impact performance too much if we achieve this?

---

While properties may be acceptable, getting location information for each value would be better, of course. For performance issue, can we store location in somewhere else instead of that AST node itself, and can we calculate it lazily?

**Comment by devongovett** [comment]
Not too sure about this approach. What do you think? https://github.com/parcel-bundler/parcel-css/pull/169
