### ISSUE TITLE
Accept an input source-map, for generating the final source-map

### ISSUE THREAD

**Issue by binyamin** [parcel-bundler/parcel-css#219]
When a stylesheet has a source-map from a previous transformation, use it to generate the new source-map.

**Use-case**: A user might transform `.scss` files into CSS, and then minify it with parcel-css.

**Comment by devongovett** [comment]
Parcel already does this. I assume you mean when using the Parcel CSS CLI?

**Comment by binyamin** [comment]
@devongovett Nope. I'm using `@parcel/css-wasm`, in Deno. Either way, I looked through the Readme and the type definitions. I couldn't find any options which accepted a source-map.

**Comment by devongovett** [comment]
We could support data urls in a `sourceMappingURL` comment, but referencing files on the filesystem or external URLs won't be supported because Parcel CSS doesn't do any filesystem operations (in WASM there is no access anyway).

I suppose we could also support a separate input string for the source map, but handling that is already possible using Parcel's source map library. Something like this:

```js
const {transform} = require('@parcel/css');
const SourceMap = require('@parcel/source-map');

let result = transform({ /* ... */ });

let prevMap = new SourceMap(PROJECT_ROOT_DIR);
prevMap.addVLQMap(previousSourceMapJSON)

let map = new SourceMap(PROJECT_ROOT_DIR);
map.addVLQMap(JSON.parse(result.map.toString()));
if (prevMap) {
  map.extends(prevMap);
}
```

**Comment by binyamin** [comment]
@devongovett Thank you. By the way, what does the `PROJECT_ROOT_DIR` variable do here? Just wondering.

**Comment by devongovett** [comment]
All file paths in the source map are stored relative to the project root directory. Typically it'll be  the root of your git repository, for example.

Btw, I'm working on support for data urls in `sourceMappingURL` comments. Will open a PR here once https://github.com/parcel-bundler/source-map/pull/109 is merged.
