### ISSUE TITLE
Suggestion: Consider switching to "browserslist-rs"

### ISSUE THREAD

**Issue by g-plane** [parcel-bundler/parcel-css#37]
There's already [browserslist-rs](https://github.com/g-plane/browserslist-rs), so we can consider switching to it.

Pros:

- It's written in Rust and "parcel-css" is also written in Rust, so integration can be easier.
- It doesn't rely on JavaScript, so if someone uses "parcel-css" as a Rust crate, he/she can also use "browserslist" feature. Also, online demo can also support this.

Cons:

- So far, "browserslist-rs" has implemented most of the features in JavaScript-based "browserslist", but not 100%, so some rarely used features can't be available.
- "Can I Use" data are bundled, while in JavaScript-based "browserslist" those data are installed as dependencies, so data statistics may not up-to-date.

**Comment by mischnic** [comment]
https://twitter.com/devongovett/status/1481369222047481858:

> There's an API to convert browserslist results into the target object expected by Parcel CSS. It's separate for performance reasons: you do this once, and then process all your files, rather than running browserslist each time.
> https://github.com/parcel-bundler/parcel-css#from-javascript

**Comment by devongovett** [comment]
Added in 7d9cec033f17c7b4cf8c0455abf9341d55adc5ad

**Comment by brycewray** [comment]
Any chance this dependency will be updated in the near future? As of today, LCSS 1.23.0 contains either v.0.12.3 or 0.12.4 (`Cargo.toml` and `Cargo.lock` don’t agree, and I know virtually zero Rust so have no idea about that); so, at best, the dependency dates back to either [Dec. 20, 2022](https://github.com/browserslist/browserslist-rs/releases/tag/v0.12.3) or [May 11, 2023](https://github.com/browserslist/browserslist-rs/releases/tag/v0.12.4), while the current version, 0.15.0, was issued [only a few days ago](https://github.com/browserslist/browserslist-rs/releases/tag/v0.15.0). Moreover, looking through the releases since 0.12.3/0.12.4, it appears there were some significant updates in browser data.

Don’t get me wrong: Lightning CSS is an amazing tool. Still, it would be nice to have more updated data behind the use of `targets`.
