### ISSUE TITLE
panicked at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by deckchairlabs** [parcel-bundler/parcel-css#63]
I'm attempting to print a StyleSheet that has a very simple rule defined.

```css
a:hover {
  color: red;
}
```

Although I'm receiving `panicked at 'internal error: entered unreachable code'` from https://github.com/parcel-bundler/parcel-css/blob/49cbb536b71e17113c5726a1797a98c41a9f0016/src/selector.rs#L327

I don't really understand what the `pseudo_classes` option of `PrinterOptions` is for

**Comment by deckchairlabs** [comment]
Ah, so it seems this is occuring when calling `to_css_string` on `SelectorList` as PseduoClass doesn't implement the `to_css_with_context` method.

**Comment by devongovett** [comment]
Hmm, we may need to expose the `ToCss` trait defined in `parcel_css` as opposed to the one in cssparser: https://github.com/parcel-bundler/parcel-css/blob/3e8f71ef3729879872e78f4cb2cc6f22cd2597ad/src/traits.rs#L18

**Comment by deckchairlabs** [comment]
Yeah, I wasn't sure how much of the able you want to expose, because it looks like the internal printer would also need to be exposed publically?

**Comment by devongovett** [comment]
Yeah. Another problem is that selectors cannot always be printed by themselves. The nesting selector `&` needs the context of all parent rules to print correctly. If we offered a standalone method to print selectors, it would only print the `&` and not combine it with the parent selectors.

**Comment by deckchairlabs** [comment]
I was thinking that maybe style rule could have a parent field?

But I'm not sure how much that would involve with changing that data structure.

I'll try some suggestions in my fork, and may open a PR if it solves my use case.

**Comment by devongovett** [comment]
Hey, sorry for the delay. This took a bit of thinking because it involves a number of traits crossing crate boundaries.

I implemented `std::fmt::Display` for `SelectorList`, which also means `ToString` is implemented. This means you don't need to use `ToCss`, you can just use `style_rule.selectors.to_string()`.

There's a default implementation in the `parcel_selectors` crate, but `parcel_css` overrides it to handle a few things differently (and avoid the unreachable issue you ran into).

I did not solve the context issue. I think it's unclear what the behavior should be if serializing an individual selector. Do you substitute the `&` for the parent selectors, or just serialize as is? I could go both ways, but I'm leaning toward the latter as that is what the CSSOM spec says for nested style rules.

**Comment by deckchairlabs** [comment]
Ah amazing! Not a problem at all. I wasn't sure about the nested selectors either, unless the spec indicates that `&` is the *direct* parent of the child? So it would translate to `.parent > .child`
