### ISSUE TITLE
Licensing isn't clear

### ISSUE THREAD

**Issue by jdm** [parcel-bundler/parcel-css#64]
https://github.com/parcel-bundler/parcel-css/blob/master/LICENSE says this project uses the MIT license, but the CSS parser code is built on the implementation in Firefox/Servo, which both use the MPL 2.0. See Q9 in https://www.mozilla.org/en-US/MPL/2.0/FAQ/. https://www.mozilla.org/en-US/MPL/license-policy/ mentions that the MIT license is compatible with the MPL 2.0, but that doesn't mean that it can be relicensed entirely.

**Comment by devongovett** [comment]
See https://github.com/parcel-bundler/parcel-css/blob/master/NOTICE. To be honest, I'm not entirely sure how to do it myself. If you have ideas on how to clarify, please let me know.

**Comment by devongovett** [comment]
Hmm I think I misunderstood how the MPL worked. I thought that it allowed distributing modifications as part of a "larger work" under a different license, but upon further research it seems that these must be in separate files. That's already the case for the selectors fork (https://github.com/parcel-bundler/parcel-css/blob/master/selectors/LICENSE), but I think this is too complicated to manage in other files that may use only portions of code from Servo since there aren't clean points to split this up. I think I will just change the license to MPL instead to keep things simple. I don't really see any downsides to doing so.

**Comment by sirinath** [comment]
Maybe you can ask Mozilla permission to use this code and relicense it under MIT.
