### ISSUE TITLE
css`inset` is not support for Safari, but it still convert to `inset` without fallback

### ISSUE THREAD

**Issue by kurobanekid** [parcel-bundler/parcel-css#65]
css`inset` is not support for Safari, but it still convert to `inset` without fallback

===  package.json ===

    "parcel": "^2.2.0",
    "browserslist": [
      "last 2 versions",
      "> 1%",
      "safari >= 11",
      "ie >= 10"
    ],

=== .parcelrc ===
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": ["...", "parcel-transformer-html-datasrc"],
    "*.css": ["@parcel/transformer-css-experimental"]
  },
  "optimizers": {
    "*.css": ["@parcel/optimizer-css"]
  },
}

=== source code ===

.foo {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
}

=== after parcel build ===
.foo{-ms-flex-pack:center;justify-content:center;-ms-flex-align:center;align-items:center;display:-ms-flexbox;display:flex;position:absolute;inset:0}

=== expect result ===
.foo{-ms-flex-pack:center;justify-content:center;-ms-flex-align:center;align-items:center;display:-ms-flexbox;display:flex;position:absolute;inset:0;top:0;right:0;bottom:0;left:0}

**Comment by devongovett** [comment]
Looking at the playground, it looks like it does work correctly with Safari 14 as the target. Safari 15 supports inset natively. [Example](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A917504%7D%2C%22source%22%3A%22.foo%20%7B%5Cnposition%3A%20absolute%3B%5Cntop%3A%200%3B%5Cnright%3A%200%3B%5Cnbottom%3A%200%3B%5Cnleft%3A%200%3B%5Cndisplay%3A%20flex%3B%5Cnflex-direction%3A%20column%3B%5Cnalign-items%3A%20flex-start%3B%5Cnjustify-content%3A%20center%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)

Perhaps you ran into #56? This was fixed in Parcel v2.2.1.
