### ISSUE TITLE
`cargo install` error: no binaries are available for install using the selected features

### ISSUE THREAD

**Issue by joelmoss** [parcel-bundler/parcel-css#78]
Trying to install the latest rust lib (1.0.0-alpha.14) with `cargo install parcel_css --version 1.0.0-alpha.14`, which I assume includes the latest changes from 1.2.0, but I get this error:

```
   Compiling parcel_css v1.0.0-alpha.14
    Finished release [optimized] target(s) in 23.92s
error: no binaries are available for install using the selected features
```

Is alpha.14 the latest release?

Also, as a side question, why is the cargo lib not versioned the same as the JS lib?

thx :)

**Comment by devongovett** [comment]
The CLI was changed to optional so that the dependencies aren't downloaded for people using the library. You can build it with the `--feature cli` option to cargo. I still haven't decided how to distribute pre-built binaries, but once those are available, installing via cargo should be rare.

> Also, as a side question, why is the cargo lib not versioned the same as the JS lib?

The Rust library is not API stable yet, whereas the JS API is. The Rust API has waaaaay more surface area because it exposes the entire AST. This is still changing pretty often, so I decided to leave the Rust package in alpha state to indicate this.
